spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/my_admin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver